/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package policine;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUI_Factura extends javax.swing.JFrame{

    /**
     * Creates new form GUI_Factura
     */
    public GUI_Factura() {
        
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Factura");
        Factura f1 = new Factura();

        String infoUsuario = "\nCliente: " + GUI_Usuario.nombre + " " + GUI_Usuario.apellido
                + "\tCedula: " + GUI_Usuario.cedula;

        String infoSnacks = "\n\nUNIDADES                DETALLE           PvP         TOTAL"
                + "\n ========================================================="
                + "\n         " + GUI_Main.unidadesProducto
                + "                   " + GUI_Main.tipoSnack
                + "           $" + GUI_Main.precioSnack + "          $" + GUI_Main.totalAPagar;

        txaDatosFactura.setText(txaDatosFactura.getText()+"======================== POLICINE ========================\n"
                + f1.mostrarFecha() + infoUsuario + infoSnacks);


    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblFactura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDatosFactura = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblFactura.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jblFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblFactura.setText("FACTURA");
        getContentPane().add(jblFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 474, 65));

        txaDatosFactura.setEditable(false);
        txaDatosFactura.setColumns(20);
        txaDatosFactura.setRows(5);
        jScrollPane1.setViewportView(txaDatosFactura);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 420, 430));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblFactura;
    private javax.swing.JTextArea txaDatosFactura;
    // End of variables declaration//GEN-END:variables
}
