package policine;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author E2
 */
public class GUI_Main extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Main
     */
    String accion[] = {"/imagenes/p1.jpg", "/imagenes/p2.jpg", "/imagenes/p3.jpg", "/imagenes/p4.jpg", "/imagenes/p5.jpg", "/imagenes/p6.jpg","/imagenes/p7.jpg","/imagenes/p8.jpg"};
    String drama[] = {"/imagenes/d1.jpg", "/imagenes/d2.jpg", "/imagenes/d3.jpg", "/imagenes/d4.jpg", "/imagenes/d5.jpg", "/imagenes/d6.jpg","/imagenes/d7.jpg","/imagenes/d8.jpg"};
    String terror[] = {"/imagenes/t1.jpg", "/imagenes/t2.jpg", "/imagenes/t3.jpg", "/imagenes/t4.jpg", "/imagenes/t5.jpg", "/imagenes/t6.jpg","/imagenes/t7.jpg","/imagenes/t8.jpg"};
    String suspenso[] = {"/imagenes/s1.jpg", "/imagenes/s2.jpg", "/imagenes/s3.jpg", "/imagenes/s4.jpg", "/imagenes/s5.jpg", "/imagenes/s6.jpg","/imagenes/s7.jpg","/imagenes/s8.jpg"};
    String aventura[] = {"/imagenes/a1.jpg", "/imagenes/a2.jpg", "/imagenes/a3.jpg", "/imagenes/a4.jpg", "/imagenes/a5.jpg", "/imagenes/a6.jpg","/imagenes/a7.jpg","/imagenes/a8.jpg"};
    String ciencia[] = {"/imagenes/c1.jpg", "/imagenes/c2.jpg", "/imagenes/c3.jpg", "/imagenes/c4.jpg", "/imagenes/c5.jpg", "/imagenes/c6.jpg","/imagenes/c7.jpg","/imagenes/c8.jpg"};
    String musical[] = {"/imagenes/m1.jpeg", "/imagenes/m2.jpg", "/imagenes/m3.jpg", "/imagenes/m4.jpg", "/imagenes/m5.jpg", "/imagenes/m6.jpg","/imagenes/m7.jpg","/imagenes/m8.jpg"};
    String infantil[] = {"/imagenes/i1.jpg", "/imagenes/i2.png", "/imagenes/i3.jpg", "/imagenes/i4.jpg", "/imagenes/i5.jpg", "/imagenes/i6.jpg","/imagenes/i7.jpg","/imagenes/i8.jpg"};

    public GUI_Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jblV2 = new javax.swing.JLabel();
        jblV3 = new javax.swing.JLabel();
        jblV5 = new javax.swing.JLabel();
        jblV1 = new javax.swing.JLabel();
        jblV6 = new javax.swing.JLabel();
        jblV7 = new javax.swing.JLabel();
        jblV4 = new javax.swing.JLabel();
        jblV8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Genero:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, 80, 27));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acción", "Drama", "Terror", "Suspenso", "Aventura", "Ciencia Ficción", "Musical", "Infantil" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 37, 229, -1));

        jblV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c1.jpg"))); // NOI18N
        jPanel1.add(jblV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 143));

        jblV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/d1.jpg"))); // NOI18N
        jPanel1.add(jblV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 105, 143));

        jblV5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p1.jpg"))); // NOI18N
        jPanel1.add(jblV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 150));

        jblV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        jPanel1.add(jblV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 143));

        jblV6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/s1.jpg"))); // NOI18N
        jPanel1.add(jblV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, 150));

        jblV7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t1.jpg"))); // NOI18N
        jPanel1.add(jblV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 100, 150));

        jblV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i1.jpg"))); // NOI18N
        jPanel1.add(jblV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 100, 140));

        jblV8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m2.jpg"))); // NOI18N
        jPanel1.add(jblV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 100, 150));

        jTabbedPane1.addTab("Inicio", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 392, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tienda", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String genero = (String) jComboBox1.getSelectedItem();
        switch (genero) {
            case "Acción":
                try {
                        URL url = this.getClass().getResource(accion[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(accion[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(accion[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(accion[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(accion[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(accion[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(accion[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(accion[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Drama": 
                try {
                        URL url = this.getClass().getResource(drama[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(drama[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(drama[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(drama[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(drama[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(drama[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(drama[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(drama[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Terror":
                try {
                        URL url = this.getClass().getResource(terror[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(terror[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(terror[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(terror[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(terror[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(terror[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(terror[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(terror[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Suspenso":
                try {
                        URL url = this.getClass().getResource(suspenso[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(suspenso[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(suspenso[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(suspenso[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(suspenso[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(suspenso[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(suspenso[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(suspenso[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Aventura":
                try {
                        URL url = this.getClass().getResource(aventura[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(aventura[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(aventura[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(aventura[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(aventura[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(aventura[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(aventura[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(aventura[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Ciencia Ficción":
                try {
                        URL url = this.getClass().getResource(ciencia[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(ciencia[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(ciencia[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(ciencia[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(ciencia[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(ciencia[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(ciencia[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(ciencia[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Musical":
                try {
                        URL url = this.getClass().getResource(musical[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(musical[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(musical[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(musical[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(musical[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(musical[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(musical[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(musical[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Infantil":
                try {
                        URL url = this.getClass().getResource(infantil[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(infantil[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(infantil[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(infantil[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(infantil[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(infantil[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(infantil[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(infantil[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel jblV1;
    public javax.swing.JLabel jblV2;
    private javax.swing.JLabel jblV3;
    private javax.swing.JLabel jblV4;
    private javax.swing.JLabel jblV5;
    private javax.swing.JLabel jblV6;
    private javax.swing.JLabel jblV7;
    private javax.swing.JLabel jblV8;
    // End of variables declaration//GEN-END:variables
}
