package policine;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class GUI_Sala extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Sala
     */
    public GUI_Sala() {
        initComponents();
        setLocationRelativeTo(null);
        generarHora();
        setTitle("Sala");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoSala = new javax.swing.ButtonGroup();
        btgHorarios = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        btnNumeroTickets = new javax.swing.JTextPane();
        btnIngresar = new javax.swing.JButton();
        btnRetroceder = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        rbtSala2D = new javax.swing.JRadioButton();
        rbtSala3D = new javax.swing.JRadioButton();
        rbtHora1 = new javax.swing.JRadioButton();
        rbtHora2 = new javax.swing.JRadioButton();
        rbtHora3 = new javax.swing.JRadioButton();
        rbtHora4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tipo de Sala:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ticket.png"))); // NOI18N
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 60, 40));

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese los números de tickets:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Elephant", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Horarios:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jScrollPane1.setViewportView(btnNumeroTickets);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 60, 30));

        btnIngresar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btnIngresar.setText("Datos Cliente");
        btnIngresar.setEnabled(false);
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 120, 30));

        btnRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back.png"))); // NOI18N
        btnRetroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetrocederActionPerformed(evt);
            }
        });
        getContentPane().add(btnRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 50, 30));

        btnGuardar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 90, 30));

        btgTipoSala.add(rbtSala2D);
        rbtSala2D.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtSala2D.setForeground(new java.awt.Color(255, 255, 255));
        rbtSala2D.setText("Sala 2D");
        getContentPane().add(rbtSala2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        btgTipoSala.add(rbtSala3D);
        rbtSala3D.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbtSala3D.setForeground(new java.awt.Color(255, 255, 255));
        rbtSala3D.setText("Sala 3D");
        getContentPane().add(rbtSala3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        btgHorarios.add(rbtHora1);
        rbtHora1.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtHora1.setForeground(new java.awt.Color(255, 255, 255));
        rbtHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtHora1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbtHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        btgHorarios.add(rbtHora2);
        rbtHora2.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtHora2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(rbtHora2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btgHorarios.add(rbtHora3);
        rbtHora3.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtHora3.setForeground(new java.awt.Color(255, 255, 255));
        rbtHora3.setSelected(true);
        rbtHora3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(rbtHora3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        btgHorarios.add(rbtHora4);
        rbtHora4.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        rbtHora4.setForeground(new java.awt.Color(255, 255, 255));
        rbtHora4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(rbtHora4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sala.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void generarHora(){
        
        int digito1 = (int)(Math.random()*10);
        int digito2 = (int)(Math.random()*10);
        int digito3 = (int)(Math.random()*5);
        int digito4 = (int)(Math.random()*5);
        
        String hora1 = digito1+digito3+":"+digito3+digito4+" pm";
        String hora2 = digito1+digito4+":"+digito4+digito3+" pm";
        String hora3 = digito2+digito3+":"+digito4+digito4+" pm";
        String hora4 = digito2+digito4+":"+digito3+digito3+" pm";
        
        rbtHora1.setText(String.valueOf(hora1));
        rbtHora2.setText(String.valueOf(hora2));
        rbtHora3.setText(String.valueOf(hora3));
        rbtHora4.setText(String.valueOf(hora4));
    }
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
           GUI_Usuario p1 =new GUI_Usuario();
           p1.setVisible(true);
           this.setVisible(false);
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnRetrocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetrocederActionPerformed
        // TODO add your handling code here:
        GUI_Main v1 = new GUI_Main();
        v1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetrocederActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
  
        
       int opcion= JOptionPane.showConfirmDialog(rootPane, "¿Desea ir a la Tienda?", "Mensaje", JOptionPane.YES_NO_OPTION);
        
       if(opcion==0){
                               
           GUI_Main m1=new GUI_Main();
           m1.setVisible(true);
    
           m1.jtbTienda.setEnabledAt(0, false);
           m1.jtbTienda.setEnabledAt(1, true);
           this.setVisible(false);
       }else{
           btnIngresar.setEnabled(true);
       }
           
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbtHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtHora1ActionPerformed
        // TODO add your handling code here:
                
    }//GEN-LAST:event_rbtHora1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Sala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Sala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgHorarios;
    private javax.swing.ButtonGroup btgTipoSala;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JTextPane btnNumeroTickets;
    private javax.swing.JButton btnRetroceder;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtHora1;
    private javax.swing.JRadioButton rbtHora2;
    private javax.swing.JRadioButton rbtHora3;
    private javax.swing.JRadioButton rbtHora4;
    private javax.swing.JRadioButton rbtSala2D;
    private javax.swing.JRadioButton rbtSala3D;
    // End of variables declaration//GEN-END:variables
}
