package policine;

import java.awt.Image;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author E2
 */
public class GUI_Main extends javax.swing.JFrame {

    int contador = 1;
    
    /**
     * Creates new form GUI_Main
     */
    
    String accion[] = {"/imagenes/p1.jpg", "/imagenes/p2.jpg", "/imagenes/p3.jpg", "/imagenes/p4.jpg", "/imagenes/p5.jpg", "/imagenes/p6.jpg","/imagenes/p7.jpg","/imagenes/p8.jpg"};
    String drama[] = {"/imagenes/d1.jpg", "/imagenes/d2.jpg", "/imagenes/d3.jpg", "/imagenes/d4.jpg", "/imagenes/d5.jpg", "/imagenes/d6.jpg","/imagenes/d7.jpg","/imagenes/d8.jpg"};
    String terror[] = {"/imagenes/t1.jpg", "/imagenes/t2.jpg", "/imagenes/t3.jpg", "/imagenes/t4.jpg", "/imagenes/t5.jpg", "/imagenes/t6.jpg","/imagenes/t7.jpg","/imagenes/t8.jpg"};
    String suspenso[] = {"/imagenes/s1.jpg", "/imagenes/s2.jpg", "/imagenes/s3.jpg", "/imagenes/s4.jpg", "/imagenes/s5.jpg", "/imagenes/s6.jpg","/imagenes/s7.jpg","/imagenes/s8.jpg"};
    String aventura[] = {"/imagenes/a1.jpg", "/imagenes/a2.jpg", "/imagenes/a3.jpg", "/imagenes/a4.jpg", "/imagenes/a5.jpg", "/imagenes/a6.jpg","/imagenes/a7.jpg","/imagenes/a8.jpg"};
    String ciencia[] = {"/imagenes/c1.jpg", "/imagenes/c2.jpg", "/imagenes/c3.jpg", "/imagenes/c4.jpg", "/imagenes/c5.jpg", "/imagenes/c6.jpg","/imagenes/c7.jpg","/imagenes/c8.jpg"};
    String musical[] = {"/imagenes/m1.jpeg", "/imagenes/m2.jpg", "/imagenes/m3.jpg", "/imagenes/m4.jpg", "/imagenes/m5.jpg", "/imagenes/m6.jpg","/imagenes/m7.jpg","/imagenes/m8.jpg"};
    String infantil[] = {"/imagenes/i1.jpg", "/imagenes/i2.png", "/imagenes/i3.jpg", "/imagenes/i4.jpg", "/imagenes/i5.jpg", "/imagenes/i6.jpg","/imagenes/i7.jpg","/imagenes/i8.jpg"};
    String productosTienda[] = {"/imagenes/canguil.jpg","/imagenes/nachos.jpg","/imagenes/papas.png","/imagenes/bebida.jpg","/imagenes/Pollo.jpg","/imagenes/hotdog.jpg","/imagenes/chocolate.jpg","/imagenes/burguer.jpg"};
    
    
    public GUI_Main() {
        initComponents();
        setLocationRelativeTo(null);
        jtbTienda.setEnabledAt(1, false);
        setTitle("Cartelera");
    }
    
    public void limpiarGUI(){
        
        txtCantidad.setText("");
        cmbTienda.setSelectedIndex(0);
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbTienda = new javax.swing.JTabbedPane();
        jblInicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jblV2 = new javax.swing.JLabel();
        jblV3 = new javax.swing.JLabel();
        jblV5 = new javax.swing.JLabel();
        jblV1 = new javax.swing.JLabel();
        jblV6 = new javax.swing.JLabel();
        jblV7 = new javax.swing.JLabel();
        jblV4 = new javax.swing.JLabel();
        jblV8 = new javax.swing.JLabel();
        jblTienda = new javax.swing.JPanel();
        PoliSnacks = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jblProductos = new javax.swing.JLabel();
        cmbTienda = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaPrecio = new javax.swing.JTextArea();
        jblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Genero:");
        jblInicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 31, 80, 27));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------- Elija una opción ----------", "Acción", "Drama", "Terror", "Suspenso", "Aventura", "Ciencia Ficción", "Musical", "Infantil" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jblInicio.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 37, 229, -1));

        jblV2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/c1.jpg"))); // NOI18N
        jblV2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV2MouseClicked(evt);
            }
        });
        jblInicio.add(jblV2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, -1, 143));

        jblV3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/d1.jpg"))); // NOI18N
        jblV3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV3MouseClicked(evt);
            }
        });
        jblInicio.add(jblV3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 105, 143));

        jblV5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/p1.jpg"))); // NOI18N
        jblV5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV5MouseClicked(evt);
            }
        });
        jblInicio.add(jblV5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 150));

        jblV1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        jblV1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV1MouseClicked(evt);
            }
        });
        jblInicio.add(jblV1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 143));

        jblV6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/s1.jpg"))); // NOI18N
        jblV6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV6MouseClicked(evt);
            }
        });
        jblInicio.add(jblV6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, 150));

        jblV7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/t1.jpg"))); // NOI18N
        jblV7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV7MouseClicked(evt);
            }
        });
        jblInicio.add(jblV7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 100, 150));

        jblV4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/i1.jpg"))); // NOI18N
        jblV4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV4MouseClicked(evt);
            }
        });
        jblInicio.add(jblV4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 100, 140));

        jblV8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m2.jpg"))); // NOI18N
        jblV8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblV8MouseClicked(evt);
            }
        });
        jblInicio.add(jblV8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 100, 150));

        jtbTienda.addTab("Inicio", jblInicio);

        PoliSnacks.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        PoliSnacks.setText("PoliSnacks");

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIngresar.setText("Ir Datos Cliente");
        btnIngresar.setActionCommand("");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        jblProductos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmbTienda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------- Elija un producto ----------", "Policanguil", "Polinachos", "Polipapas", "Polibebidas", "Polipollo", "Polihotdog", "Polidulces", "Poliburguer" }));
        cmbTienda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        cmbTienda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTiendaItemStateChanged(evt);
            }
        });

        txaPrecio.setEditable(false);
        txaPrecio.setColumns(20);
        txaPrecio.setRows(5);
        jScrollPane1.setViewportView(txaPrecio);

        jblCantidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jblCantidad.setText("Cantidad :");

        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jblTiendaLayout = new javax.swing.GroupLayout(jblTienda);
        jblTienda.setLayout(jblTiendaLayout);
        jblTiendaLayout.setHorizontalGroup(
            jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblTiendaLayout.createSequentialGroup()
                .addGroup(jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jblTiendaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresar))
                    .addGroup(jblTiendaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jblTiendaLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(cmbTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblTiendaLayout.createSequentialGroup()
                        .addComponent(jblCantidad)
                        .addGap(29, 29, 29)
                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblTiendaLayout.createSequentialGroup()
                        .addComponent(jblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
            .addGroup(jblTiendaLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(PoliSnacks)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jblTiendaLayout.setVerticalGroup(
            jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblTiendaLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(PoliSnacks)
                .addGroup(jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jblTiendaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                        .addGap(13, 13, 13)
                        .addGroup(jblTiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnIngresar)
                            .addComponent(btnGuardar)
                            .addComponent(jblCantidad)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jblTiendaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99))))
        );

        jtbTienda.addTab("Tienda", jblTienda);

        getContentPane().add(jtbTienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        String genero = (String) jComboBox1.getSelectedItem();
        switch (genero) {
            case "Acción":
                try {
                        URL url = this.getClass().getResource(accion[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(accion[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(accion[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(accion[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(accion[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(accion[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(accion[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(accion[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Drama": 
                try {
                        URL url = this.getClass().getResource(drama[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(drama[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(drama[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(drama[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(drama[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(drama[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(drama[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(drama[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Terror":
                try {
                        URL url = this.getClass().getResource(terror[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(terror[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(terror[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(terror[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(terror[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(terror[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(terror[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(terror[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Suspenso":
                try {
                        URL url = this.getClass().getResource(suspenso[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(suspenso[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(suspenso[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(suspenso[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(suspenso[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(suspenso[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(suspenso[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(suspenso[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Aventura":
                try {
                        URL url = this.getClass().getResource(aventura[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(aventura[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(aventura[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(aventura[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(aventura[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(aventura[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(aventura[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(aventura[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Ciencia Ficción":
                try {
                        URL url = this.getClass().getResource(ciencia[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(ciencia[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(ciencia[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(ciencia[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(ciencia[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(ciencia[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(ciencia[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(ciencia[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Musical":
                try {
                        URL url = this.getClass().getResource(musical[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(musical[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(musical[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(musical[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(musical[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(musical[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(musical[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(musical[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
            case "Infantil":
                try {
                        URL url = this.getClass().getResource(infantil[0]);
                        Image img1 = ImageIO.read(url);
                        jblV1.setIcon(new ImageIcon(img1));
                        url = this.getClass().getResource(infantil[1]);
                        Image img2 = ImageIO.read(url);
                        jblV2.setIcon(new ImageIcon(img2));
                        url = this.getClass().getResource(infantil[2]);
                        Image img3 = ImageIO.read(url);
                        jblV3.setIcon(new ImageIcon(img3));
                        url = this.getClass().getResource(infantil[3]);
                        Image img4 = ImageIO.read(url);
                        jblV4.setIcon(new ImageIcon(img4));
                        url = this.getClass().getResource(infantil[4]);
                        Image img5 = ImageIO.read(url);
                        jblV5.setIcon(new ImageIcon(img5));
                        url = this.getClass().getResource(infantil[5]);
                        Image img6 = ImageIO.read(url);                                
                        jblV6.setIcon(new ImageIcon(img6));
                        url = this.getClass().getResource(infantil[6]);
                        Image img7 = ImageIO.read(url);                                
                        jblV7.setIcon(new ImageIcon(img7));
                        url = this.getClass().getResource(infantil[7]);
                        Image img8 = ImageIO.read(url);                                
                        jblV8.setIcon(new ImageIcon(img8));
                    } catch (Exception e) {
                    }
                break;
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jblV1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV1MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV1MouseClicked

    private void jblV2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV2MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV2MouseClicked

    private void jblV3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV3MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV3MouseClicked

    private void jblV4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV4MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV4MouseClicked

    private void jblV5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV5MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV5MouseClicked

    private void jblV6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV6MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV6MouseClicked

    private void jblV7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV7MouseClicked
        // TODO add your handling code here:
        GUI_Sala sala = new GUI_Sala();
        sala.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV7MouseClicked

    private void jblV8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblV8MouseClicked
        // TODO add your handling code here:
        GUI_Usuario usuario = new GUI_Usuario();
        usuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblV8MouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        GUI_Usuario usuario = new GUI_Usuario();
        usuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void cmbTiendaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTiendaItemStateChanged
        // TODO add your handling code here:
    
        String opcion = (String) cmbTienda.getSelectedItem();
        URL url;
        switch (opcion) {
            case "Policanguil":
                try {
                    url = this.getClass().getResource(productosTienda[0]);
                    Image img1 = ImageIO.read(url);
                    jblProductos.setIcon(new ImageIcon(img1));
                   
                } catch (Exception e) {
                }
                break;
            case "Polinachos":
                try {
                    url = this.getClass().getResource(productosTienda[1]);
                    Image img2 = ImageIO.read(url);
                    jblProductos.setIcon(new ImageIcon(img2));

                } catch (Exception e) {
                }
                break;
            case "Polipapas":
                try {
                        url = this.getClass().getResource(productosTienda[2]);
                        Image img3 = ImageIO.read(url);
                        jblProductos.setIcon(new ImageIcon(img3));                        
                    } catch (Exception e) {
                    }
                break;
            case "Polibebidas":
                try {
                        url = this.getClass().getResource(productosTienda[3]);
                        Image img4 = ImageIO.read(url);
                        jblProductos.setIcon(new ImageIcon(img4));                       
                    } catch (Exception e) {
                    }
                break;
            case "Polipollo":
                try {
                        url = this.getClass().getResource(productosTienda[4]);
                        Image img5 = ImageIO.read(url);
                        jblProductos.setIcon(new ImageIcon(img5));
                        
                    } catch (Exception e) {
                    }
                break;
            case "Polihotdog":
                try {
                        url = this.getClass().getResource(productosTienda[5]);
                        Image img6 = ImageIO.read(url);
                        jblProductos.setIcon(new ImageIcon(img6));
                        
                    } catch (Exception e) {
                    }
                break;
            case "Polidulces":
                try {
                        url = this.getClass().getResource(productosTienda[6]);
                        Image img7 = ImageIO.read(url);
                        jblProductos.setIcon(new ImageIcon(img7));
                        
                    } catch (Exception e) {
                    }
                break;
            case "Poliburguer":
                try {
                        url = this.getClass().getResource(productosTienda[7]);
                        Image img8 = ImageIO.read(url);
                        jblProductos.setIcon(new ImageIcon(img8));
                       
                    } catch (Exception e) {
                    }
                break;
        }
    }//GEN-LAST:event_cmbTiendaItemStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
        String tipoSnack =(String)cmbTienda.getSelectedItem();
        
        double precioSnack;
        if (tipoSnack.equalsIgnoreCase("Policanguil")){
            precioSnack=3.50;
        }else if(tipoSnack.equalsIgnoreCase("Polinachos")){
            precioSnack=4.00;
        }else if (tipoSnack.equalsIgnoreCase("Polipapas")){
            precioSnack=2.50;
        } else if(tipoSnack.equalsIgnoreCase("Polibebidas")){
            precioSnack=3.00;
        }else if (tipoSnack.equalsIgnoreCase("Polipollo")){
            precioSnack=4.50;
         }else if(tipoSnack.equalsIgnoreCase("Polihotdog")){
            precioSnack=1.50;
        }else if (tipoSnack.equalsIgnoreCase("Polidulces")){
            precioSnack=2.50;
        }else{
            precioSnack=2.00;
        }
        
        int unidades=Integer.parseInt(txtCantidad.getText());
        double total=calcularTotal(unidades, precioSnack);
        
        Snacks s=new Snacks(unidades, tipoSnack, precioSnack,total );
        
                
        txaPrecio.setText(txaPrecio.getText()+s.toString());
        
        limpiarGUI();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        // TODO add your handling code here:
                char validacion1=evt.getKeyChar();
        if(Character.isLetter(validacion1)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permiten Numeros");
        }
    }//GEN-LAST:event_txtCantidadKeyTyped
 
    
    
    public double calcularTotal(int unidades, double precio) {

        double total = unidades * precio;

        return total;
    }

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PoliSnacks;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JComboBox<String> cmbTienda;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblCantidad;
    private javax.swing.JPanel jblInicio;
    private javax.swing.JLabel jblProductos;
    private javax.swing.JPanel jblTienda;
    private javax.swing.JLabel jblV1;
    public javax.swing.JLabel jblV2;
    private javax.swing.JLabel jblV3;
    private javax.swing.JLabel jblV4;
    private javax.swing.JLabel jblV5;
    private javax.swing.JLabel jblV6;
    private javax.swing.JLabel jblV7;
    private javax.swing.JLabel jblV8;
    public javax.swing.JTabbedPane jtbTienda;
    private javax.swing.JTextArea txaPrecio;
    private javax.swing.JTextField txtCantidad;
    // End of variables declaration//GEN-END:variables
}
